# Generated by Django 2.1 on 2019-01-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='position',
            new_name='candidate',
        ),
    ]
